language: minimal

dist: xenial
addons:
  apt:
    packages:
      - docker

git:
  depth: 1
  submodules: false

before_script:
  - docker-compose run terraform init -backend-config="token=${TERRAFORM_TOKEN}"

jobs:
  include:
    -
      if: type = pull_request
      script:
        - docker-compose run terraform plan
    -
      if: branch = master AND type = push
      script:
        - docker-compose run terraform apply -target=module.dev -auto-approve
    -
      if: branch = master AND tag IS present
      script:
        - docker-compose run terraform apply -auto-approve
