language: minimal

dist: xenial
addons:
  apt:
    packages:
      - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose run terraform init -backend-config=\"token=${TERRAFORM_TOKEN}\"

jobs:
  include:
    -
      if: branch = develop AND type = pull_request
      script:
        - docker-compose run terraform plan -target=module.dev
    -
      if: branch = develop AND type = push
      script:
        - docker-compose run terraform apply -target=module.dev -auto-approve
    -
      if: branch = master AND type = pull_request
      script:
        - docker-compose run terraform plan
    -
      if: branch = master AND type = push
      script:
        - docker-compose run terraform apply -auto-approve
