version: '3.6'

services:
  terraform:
    image: hashicorp/terraform:0.12.6
    environment:
      - TF_VAR_aws_dev_access_key
      - TF_VAR_aws_dev_secret_key
      - TF_VAR_aws_prod_access_key
      - TF_VAR_aws_prod_secret_key
    working_dir: /app
    volumes:
      - ./terraform:/app
